# Generated by Django 5.0 on 2023-12-17 14:02

import student_management_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_remove_document_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=student_management_app.models.get_upload_path),
        ),
    ]
